apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-kobruh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-kobruh
    app.kubernetes.io/part-of: jvm-build-suite-application-sqsl
  name: jvm-build-suite-component-kobruh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-kobruh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-kobruh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-ofwz-tenant/jvm-build-suite-application-sqsl/jvm-build-suite-component-kobruh@sha256:e001d495adcdec8b7d6dff015ddbf4a5a8cdfeb27c609fe738ec940136a18117
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
